version: "0.5"
log_location: ./.dev/process-compose.log
log_level: debug

processes:
  redpanda:
    command: rpk container start -n 1 --kafka-ports 9092
    shutdown:
      command: rpk container purge
    readiness_probe:
      exec:
        command: "rpk cluster info"
      initial_delay_seconds: 5
      period_seconds: 5
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 10
    availability:
      restart: on_failure
